languageCode = "en"
languageName = "English"
weight = 1
title = "Bytecodesky"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  description = "A personal blog form Red Team topics, open source security, capture the flags, and all things information security"
  copyright = "Bytecodesky | Angel Barre 2024"

[author]
  name = "Angel Barre"
  email = "skynetoffc@gmail.com"
  image = "logo.png"
  imageQuality = 96
  headline = "Debugging: Removing the needles from the haystack."
  bio = "I'am a Cybersecurity Researcher and passionate Backend Developer and i like play much CTFs."
  links = [
    { email = "mailto:skynetoffc@gmail.com" },
    { link = "https://bytecodesky.me/" },
#     { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
#     { apple = "https://www.apple.com" },
#     { blogger = "https://username.blogspot.com/" },
#     { bluesky = "https://bsky.app/profile/username" },
    { codepen = "https://codepen.io/bytecodesky" },
    { dev = "https://dev.to/bytecodesky" },
#     { discord = "https://discord.gg/invitecode" },
#     { dribbble = "https://dribbble.com/username" },
#     { facebook = "https://facebook.com/username" },
#     { flickr = "https://www.flickr.com/photos/username/" },
#     { foursquare = "https://foursquare.com/username" },
    { github = "https://github.com/bytecodesky" },
#     { gitlab = "https://gitlab.com/username" },
#     { google = "https://www.google.com/" },
#     { hashnode = "https://username.hashnode.dev" },
#     { instagram = "https://instagram.com/username" },
#     { itch-io = "https://username.itch.io" },
#     { keybase = "https://keybase.io/username" },
#     { kickstarter = "https://www.kickstarter.com/profile/username" },
#     { lastfm = "https://lastfm.com/user/username" },
    { linkedin = "https://linkedin.com/in/angel-barre" },
#     { mastodon = "https://mastodon.instance/@username" },
#     { medium = "https://medium.com/username" },
#     { microsoft = "https://www.microsoft.com/" },
#     { orcid = "https://orcid.org/userid" },
#     { patreon = "https://www.patreon.com/username" },
#     { pinterest = "https://pinterest.com/username" },
#     { reddit = "https://reddit.com/user/username" },
#     { researchgate = "https://www.researchgate.net/profile/username" },
#     { slack = "https://workspace.url/team/userid" },
#     { snapchat = "https://snapchat.com/add/username" },
#     { soundcloud = "https://soundcloud.com/username" },
#     { spotify = "https://open.spotify.com/user/userid" },
    { stack-overflow = "https://stackoverflow.com/users/26590748/angel-barre" },
#     { steam = "https://steamcommunity.com/profiles/userid" },
#     { telegram = "https://t.me/bytecodesky" },
#     { threads = "https://www.threads.net/@username" },
#     { tiktok = "https://tiktok.com/@username" },
#     { tumblr = "https://username.tumblr.com" },
#     { twitch = "https://twitch.tv/username" },
#     { twitter = "https://x.com/bytecodesky" },
    { x-twitter = "https://x.com/bytecodesky" },
#     { whatsapp = "https://wa.me/phone-number" },
#     { youtube = "https://youtube.com/username" },
#     { ko-fi = "https://ko-fi.com/username" },
#     { codeberg = "https://codeberg.org/username"},
  ]
